---
latitude: '40.750613'
longitude: "-73.977095"
map_zoom: 12

name: Demo Hotel
email: support@traveltripper.com
phone_number: 123-123-1234
address:
  street1: Lexington Ave
  state: NY
  city: New York
  zip_code: 
default_currency: USD
default_timezone: America/New_York
_hotel_id: NYCTMC
_portal_id: thepierreny
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  google_location: 
    type: location
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  map_zoom:
    type: integer
    latitude:
      type: float
    longitude:
      type: float
logo:
  alt: ''
  caption: ''
  description: ''
