---
latitude: '52.070375'
longitude: "-9.574189"
map_zoom: 12
name: Demo Hotel
email: support@traveltripper.com
phone_number: 123-123-1234
address:
  street1: Lexington Ave
  state: NY
  city: New York
  zip_code: 
default_currency: USD
default_timezone: America/New_York
_hotel_id: NYCTP
_portal_id: thepierreny
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.1
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  map_zoom:
    type: integer
    latitude:
      type: float
    longitude:
      type: float
logo:
  name: fred-mouniguet-102116
  content_type: image/jpeg
  date_added: 2019-03-01-160536
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_crop,h_747,w_2527,x_179,y_1536/c_fill,g_faces,h_140,w_140/v1551474337/vobnmk5l2mfiszzjwazm.jpg"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_crop,h_747,w_2527,x_179,y_1536/c_fit,h_300,w_300/v1551474337/vobnmk5l2mfiszzjwazm.jpg"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_crop,h_747,w_2527,x_179,y_1536/c_fit,h_768,w_768/v1551474337/vobnmk5l2mfiszzjwazm.jpg"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_crop,h_747,w_2527,x_179,y_1536/c_fit,h_992,w_992/v1551474337/vobnmk5l2mfiszzjwazm.jpg"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_crop,h_747,w_2527,x_179,y_1536/c_fit,h_1200,w_1200/v1551474337/vobnmk5l2mfiszzjwazm.jpg"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1551474337/vobnmk5l2mfiszzjwazm.jpg"
  width: 4059
  height: 2283
  format: jpg
  url: "//res.cloudinary.com/traveltripperweb/image/upload/v1551474337/vobnmk5l2mfiszzjwazm.jpg"
  resource_type: image
  size: 8060975
  git_file_name: _assets/image_data/fred-mouniguet-102116.jpg.json
  path: "//res.cloudinary.com/traveltripperweb/image/upload/v1551474337/vobnmk5l2mfiszzjwazm.jpg"
  file_size: 
  alt: fred-mouniguet-102116
  crop:
    origin:
      x: 179
      y: 1536
    width: 2527
    height: 747
